const BingoDefault = [
  "mutters / murmurs",
  "recursive loops",
  "tapestry / lattice",
  "grunts / snorts / barks",
  "intones / echoes",
  "whispers / barely audible / softly",
  "breathing / living rooms",
  "strength / determination",
  "darting eyes",
  "pulses / signal",
  "mind / heart races",
  "remembered / unforgotten",
  "seen / heard / listens",
  "not X, just Y",
  "rule of 3's",
  "watching / waiting.",
  "em-dashes",
  "echoes / noise",
  "nonsense similes",
  "it holds",
  "ellipses at second to last... word",
  "Elara and co.",
  "mechanical / measured / surgical",
  "{adj} precision",
  "continuity errors",
];

module.exports = BingoDefault;
